### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Yanis002** [Yanis42/DecompAssetsFixer#2]
- [ ] Enhance the existing code to reduce execution time
- [x] Add casts to segment names for scenes and rooms
- [x] Use enum names for entrances
